### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by LJMSU**
Code formatting, some changes to variable names, and much more.

### CODE REVIEW

**Comment by LJMSU** [comment]
Don't merge this PR yet

**Comment by NETtoSan** [comment]
lol no

**Comment by LJMSU** [comment]
wut

**Comment by LJMSU** [comment]
alright you can merge it now

**Comment by NETtoSan** [comment]
lol no

**Comment by LJMSU** [comment]
tysm

**Pull request merged**
